approve_by_comment: true
approve_regex: ':\+1:'
reset_on_push: true
author_approval: ignored
reviewers:
    -
        name: users
        required: 2
        members:
            - cjllanwarne
            - Horneth
            - scottfrazer
            - mcovarr
            - geoffjentry
            - kshakir
            - francares
            - guaravs90
            - jainh
