language: scala
scala:
  - 2.11.6
jdk:
  - oraclejdk8
before_script:
  - mysql -e "create database IF NOT EXISTS cromwell_test;"

script: sbt -Dbackend.shared-filesystem.localization.0=copy clean coverage nodocker:test assembly
after_success: sbt coveralls
