sudo: required
dist: trusty
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
env:
  global:
    - CENTAUR_BRANCH=79dc5f9f0f6ca6aedb5b13358d47b0c9c4156d51
  matrix:
    # Setting this variable twice will cause the 'script' section to run twice with the respective env var invoked
    - BUILD_TYPE=sbt
    - BUILD_TYPE=centaurJes
    - BUILD_TYPE=centaurLocal
script:
  - src/bin/travis/test.sh
after_success:
  - src/bin/travis/afterSuccess.sh
deploy:
  provider: script
  script: src/bin/travis/publishRelease.sh
  on:
    tags: true
